site_name: Silas Maths

repo_name: Silas Maths
repo_url: https://github.com/silaspe/maths

nav:
  - Home: README.md
  - Calculus: derivatives.md
  - Calculus II: calculus_2.md
  - Complex: complex.md
  - Hyperbolic: hyperbolic.md
  - Trigonometry: trigonometry.md

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


use_directory_urls: false

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: "#"
  - codehilite
  - admonition
  - markdown_include.include:
      base_path: docs
  - mdx_math:
      enable_dollar_delimiter: True 
  # - pymdownx.highlight:
  #     anchor_linenums: true
  #     line_spans: __span
  #     pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.extra
  - markdown.extensions.codehilite
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

